#!/usr/bin/env python
import sys
sys.path.append('../ofxclient')
import cherrypy, ofxclient.webapp

config = {
    '/': {
        'tools.staticdir.root': ofxclient.webapp.html_dir
    },
    '/favicon.ico': {
        'tools.staticfile.on': True,
        'tools.staticfile.filename': ofxclient.webapp.html_dir + '/favicon.ico'
    },
    '/static': {
        'tools.staticdir.on': True,
        'tools.staticdir.dir': "static"
    }
}

cherrypy.quickstart(ofxclient.webapp.Root(),config=config)
